title: Project
preset: page

status:
  draft: Draft
  listed: Published

fields:
  published:
    label: Published on
    type: date
    display: MM/DD/YYYY
    width: 1/2
  category:
    label: Category
    type: tags
    width: 1/2
  intro:
    type: textarea
    size: small
  text:
    type: blocks


sidebar:
  cover:
    type: files
    label: Cover
    layout: cards
    info: "{{ file.dimensions }}"
    template: cover
    min: 1
    max: 3
  gallery:
    type: files
    label: Gallery
    template: image