title: Site

columns:
  main:
    width: 1/3
    sections:
      fields:
        type: fields
        fields:
          Description:
            type: textarea
            size: small
          Logo:
            type: files

  sidebar:
    width: 2/3
    sections:
      pages:
        type: pages
